from .base import UnexpectedError


class DAOError(UnexpectedError):
    pass
